### ISSUE TITLE
Meeting Guide App

### ISSUE THREAD

**Issue by jduckett** [code4recovery/wagtail-meeting-guide#4]
Searching the documentation for all of code4recovery I could not find any links pointing to the actual meeting guide app source code. Is the Meeting Guide App a closed source project?

**Comment by donwatkins** [comment]
https://github.com/code4recovery/wagtail-meeting-guideDonOn May 27, 2024, at 4:12 PM, Jeff Duckett ***@***.***> wrote:﻿
Searching the documentation for all of code4recovery I could not find any links pointing to the actual meeting guide app source code. Is the Meeting Guide App a closed source project?

**Comment by FlipperPA** [comment]
@jduckett The Meeting Guide App itself isn't maintained by Code for Recovery. @joshreisner was the original developer, but it was handed over to GSO to develop further a few years ago.

**Comment by jduckett** [comment]
is the code for the android app available to the public. I'm interested in it.

**Comment by FlipperPA** [comment]
@jduckett I don't believe it is. You can get in contact with the GSO team here: https://meetingguide.helpdocs.io/category/eebenj2xql-connecting-to-meeting-guide

The CONTACT button is in the top right. They're pretty responsive.

**Comment by jduckett** [comment]
Thank you very much. I'm a retired developer and simply have interest in
the meeting guide app. I really want to see how it is coded.

peace
